spring:
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#  h2:
#    console:
#      enable: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

server:
  port: 8085